-- =====================================================================
-- 20260803123000 — seed AP districts and assembly constituencies
--
-- Authoritative reference data: the 26 districts created by the 2022
-- reorganisation, and all 175 assembly constituencies with their
-- Election Commission numbers.
--
-- NOT derived from member data. The production export contains 39
-- district spellings for 26 real districts (Anantapur/Ananthapuramu,
-- East Godavari/East_Godavari, Kadapa/Kadapa_YSR_Kadapa/YSR), plus
-- Telangana districts, and 51 constituencies claimed by more than one
-- district. Seeding from that would make the mess permanent. Those
-- values get reconciled AGAINST this table instead.
--
-- Idempotent: safe to re-run.
-- =====================================================================

INSERT INTO public.ap_districts (id, name, region) VALUES
  (1, 'Srikakulam', 'Coastal Andhra'),
  (2, 'Parvathipuram Manyam', 'Coastal Andhra'),
  (3, 'Vizianagaram', 'Coastal Andhra'),
  (4, 'Visakhapatnam', 'Coastal Andhra'),
  (5, 'Anakapalli', 'Coastal Andhra'),
  (6, 'Alluri Sitharama Raju', 'Coastal Andhra'),
  (7, 'Kakinada', 'Coastal Andhra'),
  (8, 'Dr. B.R. Ambedkar Konaseema', 'Coastal Andhra'),
  (9, 'East Godavari', 'Coastal Andhra'),
  (10, 'West Godavari', 'Coastal Andhra'),
  (11, 'Eluru', 'Coastal Andhra'),
  (12, 'Krishna', 'Coastal Andhra'),
  (13, 'NTR', 'Coastal Andhra'),
  (14, 'Guntur', 'Coastal Andhra'),
  (15, 'Palnadu', 'Coastal Andhra'),
  (16, 'Bapatla', 'Coastal Andhra'),
  (17, 'Prakasam', 'Coastal Andhra'),
  (18, 'Sri Potti Sriramulu Nellore', 'Coastal Andhra'),
  (19, 'Kurnool', 'Rayalaseema'),
  (20, 'Nandyal', 'Rayalaseema'),
  (21, 'Anantapur', 'Rayalaseema'),
  (22, 'Sri Sathya Sai', 'Rayalaseema'),
  (23, 'YSR Kadapa', 'Rayalaseema'),
  (24, 'Annamayya', 'Rayalaseema'),
  (25, 'Tirupati', 'Rayalaseema'),
  (26, 'Chittoor', 'Rayalaseema')
ON CONFLICT (id) DO UPDATE
  SET name = EXCLUDED.name, region = EXCLUDED.region;


INSERT INTO public.ap_constituencies (id, name, district_id, is_reserved) VALUES
  (1, 'Ichchapuram', 1, NULL),
  (2, 'Palasa', 1, NULL),
  (3, 'Tekkali', 1, NULL),
  (4, 'Pathapatnam', 1, NULL),
  (5, 'Srikakulam', 1, NULL),
  (6, 'Amadalavalasa', 1, NULL),
  (7, 'Etcherla', 1, NULL),
  (8, 'Narasannapeta', 1, NULL),
  (9, 'Rajam', 1, 'SC'),
  (10, 'Palakonda', 2, 'ST'),
  (11, 'Kurupam', 2, 'ST'),
  (12, 'Parvathipuram', 2, 'SC'),
  (13, 'Salur', 2, 'ST'),
  (14, 'Bobbili', 3, NULL),
  (15, 'Cheepurupalli', 3, NULL),
  (16, 'Gajapathinagaram', 3, NULL),
  (17, 'Nellimarla', 3, NULL),
  (18, 'Vizianagaram', 3, NULL),
  (19, 'Srungavarapukota', 3, NULL),
  (20, 'Bhimili', 4, NULL),
  (21, 'Visakhapatnam East', 4, NULL),
  (22, 'Visakhapatnam South', 4, NULL),
  (23, 'Visakhapatnam North', 4, NULL),
  (24, 'Visakhapatnam West', 4, NULL),
  (25, 'Gajuwaka', 4, NULL),
  (26, 'Chodavaram', 5, NULL),
  (27, 'Madugula', 5, NULL),
  (28, 'Araku Valley', 6, 'ST'),
  (29, 'Paderu', 6, 'ST'),
  (30, 'Anakapalle', 5, NULL),
  (31, 'Pendurthi', 4, NULL),
  (32, 'Elamanchili', 5, NULL),
  (33, 'Payakaraopet', 5, 'SC'),
  (34, 'Narsipatnam', 5, NULL),
  (35, 'Tuni', 7, NULL),
  (36, 'Prathipadu', 7, NULL),
  (37, 'Pithapuram', 7, NULL),
  (38, 'Kakinada Rural', 7, NULL),
  (39, 'Peddapuram', 7, NULL),
  (40, 'Anaparthy', 9, NULL),
  (41, 'Kakinada City', 7, NULL),
  (42, 'Ramachandrapuram', 8, NULL),
  (43, 'Mummidivaram', 8, NULL),
  (44, 'Amalapuram', 8, 'SC'),
  (45, 'Razole', 8, 'SC'),
  (46, 'Gannavaram', 8, 'SC'),
  (47, 'Kothapeta', 8, NULL),
  (48, 'Mandapeta', 9, NULL),
  (49, 'Rajanagaram', 9, NULL),
  (50, 'Rajahmundry City', 9, NULL),
  (51, 'Rajahmundry Rural', 9, NULL),
  (52, 'Jaggampeta', 9, NULL),
  (53, 'Rampachodavaram', 6, 'ST'),
  (54, 'Kovvur', 10, 'SC'),
  (55, 'Nidadavole', 10, NULL),
  (56, 'Achanta', 10, NULL),
  (57, 'Palacole', 10, NULL),
  (58, 'Narasapuram', 10, NULL),
  (59, 'Bhimavaram', 10, NULL),
  (60, 'Undi', 10, NULL),
  (61, 'Tanuku', 10, NULL),
  (62, 'Tadepalligudem', 10, NULL),
  (63, 'Unguturu', 11, NULL),
  (64, 'Denduluru', 11, NULL),
  (65, 'Eluru', 11, NULL),
  (66, 'Gopalapuram', 11, 'SC'),
  (67, 'Polavaram', 11, 'ST'),
  (68, 'Chintalapudi', 11, 'SC'),
  (69, 'Tiruvuru', 13, 'SC'),
  (70, 'Nuzvid', 11, NULL),
  (71, 'Gannavaram', 12, NULL),
  (72, 'Gudivada', 12, NULL),
  (73, 'Kaikalur', 11, NULL),
  (74, 'Pedana', 12, NULL),
  (75, 'Machilipatnam', 12, NULL),
  (76, 'Avanigadda', 12, NULL),
  (77, 'Pamarru', 12, 'SC'),
  (78, 'Penamaluru', 12, NULL),
  (79, 'Vijayawada West', 13, NULL),
  (80, 'Vijayawada Central', 13, NULL),
  (81, 'Vijayawada East', 13, NULL),
  (82, 'Mylavaram', 13, NULL),
  (83, 'Nandigama', 13, 'SC'),
  (84, 'Jaggayyapeta', 13, NULL),
  (85, 'Pedakurapadu', 15, NULL),
  (86, 'Tadikonda', 14, 'SC'),
  (87, 'Mangalagiri', 14, NULL),
  (88, 'Ponnuru', 16, NULL),
  (89, 'Vemuru', 16, 'SC'),
  (90, 'Repalle', 16, NULL),
  (91, 'Tenali', 14, NULL),
  (92, 'Bapatla', 16, NULL),
  (93, 'Prathipadu', 14, 'SC'),
  (94, 'Guntur West', 14, NULL),
  (95, 'Guntur East', 14, NULL),
  (96, 'Chilakaluripet', 15, NULL),
  (97, 'Narasaraopet', 15, NULL),
  (98, 'Sattenapalle', 15, NULL),
  (99, 'Vinukonda', 15, NULL),
  (100, 'Gurajala', 15, NULL),
  (101, 'Macherla', 15, NULL),
  (102, 'Yerragondapalem', 17, 'SC'),
  (103, 'Darsi', 17, NULL),
  (104, 'Parchur', 16, NULL),
  (105, 'Addanki', 16, NULL),
  (106, 'Chirala', 16, NULL),
  (107, 'Santhanuthalapadu', 17, 'SC'),
  (108, 'Ongole', 17, NULL),
  (109, 'Kandukur', 18, NULL),
  (110, 'Kondapi', 17, 'SC'),
  (111, 'Markapuram', 17, NULL),
  (112, 'Giddalur', 17, NULL),
  (113, 'Kanigiri', 17, NULL),
  (114, 'Kavali', 18, NULL),
  (115, 'Atmakur', 18, NULL),
  (116, 'Kovur', 18, NULL),
  (117, 'Nellore City', 18, NULL),
  (118, 'Nellore Rural', 18, NULL),
  (119, 'Sarvepalli', 18, NULL),
  (120, 'Gudur', 25, 'SC'),
  (121, 'Sullurpeta', 25, 'SC'),
  (122, 'Venkatagiri', 25, NULL),
  (123, 'Udayagiri', 18, NULL),
  (124, 'Badvel', 23, 'SC'),
  (125, 'Rajampet', 24, NULL),
  (126, 'Kadapa', 23, NULL),
  (127, 'Kodur', 24, 'SC'),
  (128, 'Rayachoti', 24, NULL),
  (129, 'Pulivendla', 23, NULL),
  (130, 'Kamalapuram', 23, NULL),
  (131, 'Jammalamadugu', 23, NULL),
  (132, 'Proddatur', 23, NULL),
  (133, 'Mydukur', 23, NULL),
  (134, 'Alur', 19, NULL),
  (135, 'Adoni', 19, NULL),
  (136, 'Emmiganur', 19, NULL),
  (137, 'Mantralayam', 19, NULL),
  (138, 'Kurnool', 19, NULL),
  (139, 'Panyam', 20, NULL),
  (140, 'Nandikotkur', 20, 'SC'),
  (141, 'Kodumur', 19, 'SC'),
  (142, 'Yemmiganur', 19, NULL),
  (143, 'Nandyal', 20, NULL),
  (144, 'Banaganapalle', 20, NULL),
  (145, 'Dhone', 20, NULL),
  (146, 'Pattikonda', 19, NULL),
  (147, 'Kalyandurg', 21, NULL),
  (148, 'Rayadurg', 21, NULL),
  (149, 'Uravakonda', 21, NULL),
  (150, 'Guntakal', 21, NULL),
  (151, 'Tadpatri', 21, NULL),
  (152, 'Singanamala', 21, 'SC'),
  (153, 'Anantapur Urban', 21, NULL),
  (154, 'Kadiri', 22, NULL),
  (155, 'Raptadu', 21, NULL),
  (156, 'Madakasira', 22, 'SC'),
  (157, 'Hindupur', 22, NULL),
  (158, 'Penukonda', 22, NULL),
  (159, 'Puttaparthi', 22, NULL),
  (160, 'Dharmavaram', 22, NULL),
  (161, 'Kadiri Rural', 22, NULL),
  (162, 'Thamballapalle', 24, NULL),
  (163, 'Pileru', 24, NULL),
  (164, 'Madanapalle', 24, NULL),
  (165, 'Punganur', 26, NULL),
  (166, 'Chandragiri', 25, NULL),
  (167, 'Tirupati', 25, NULL),
  (168, 'Srikalahasti', 25, NULL),
  (169, 'Satyavedu', 25, 'SC'),
  (170, 'Nagari', 26, NULL),
  (171, 'Gangadhara Nellore', 26, 'SC'),
  (172, 'Chittoor', 26, NULL),
  (173, 'Puthalapattu', 26, 'SC'),
  (174, 'Palamaner', 26, NULL),
  (175, 'Kuppam', 26, NULL)
ON CONFLICT (id) DO UPDATE
  SET name        = EXCLUDED.name,
      district_id = EXCLUDED.district_id,
      is_reserved = EXCLUDED.is_reserved;


-- =====================================================================
-- Verify
-- =====================================================================
DO $$
DECLARE d int; c int; orphan int;
BEGIN
  SELECT count(*) INTO d FROM public.ap_districts;
  SELECT count(*) INTO c FROM public.ap_constituencies;
  SELECT count(*) INTO orphan FROM public.ap_constituencies x
    WHERE NOT EXISTS (SELECT 1 FROM public.ap_districts y WHERE y.id = x.district_id);
  IF d <> 26  THEN RAISE EXCEPTION 'expected 26 districts, found %', d;  END IF;
  IF c <> 175 THEN RAISE EXCEPTION 'expected 175 constituencies, found %', c; END IF;
  IF orphan > 0 THEN RAISE EXCEPTION '% constituencies point at a missing district', orphan; END IF;
  RAISE NOTICE 'AP geography seeded: % districts, % constituencies', d, c;
END $$;
